export const foods = [
  { name: "Pirinç", group: "Glutensiz tahıl", risk: "guvenli" },
  { name: "Kinoa", group: "Glutensiz tahıl", risk: "guvenli" },
  { name: "Karabuğday", group: "Glutensiz tahıl", risk: "guvenli" },
  { name: "Mısır", group: "Glutensiz tahıl", risk: "dikkatli" },
  { name: "Yulaf (glutensiz sertifikalı)", group: "Glutensiz tahıl", risk: "dikkatli" },
  { name: "Patates", group: "Sebze", risk: "guvenli" },
  { name: "Tatlı patates", group: "Sebze", risk: "dikkatli" },
  { name: "Havuç", group: "Sebze", risk: "guvenli" },
  { name: "Kabak", group: "Sebze", risk: "guvenli" },
  { name: "Ispanak", group: "Sebze", risk: "guvenli" },
  { name: "Salatalık", group: "Sebze", risk: "guvenli" },
  { name: "Marul", group: "Sebze", risk: "guvenli" },
  { name: "Domates", group: "Sebze", risk: "dikkatli" },
  { name: "Patlıcan", group: "Sebze", risk: "dikkatli" },
  { name: "Biber", group: "Sebze", risk: "dikkatli" },
  { name: "Brokoli", group: "Sebze", risk: "dikkatli" },
  { name: "Karnabahar", group: "Sebze", risk: "riskli" },
  { name: "Mantar", group: "Sebze", risk: "riskli" },
  { name: "Sarımsak", group: "Sebze", risk: "riskli" },
  { name: "Soğan", group: "Sebze", risk: "riskli" },
  { name: "Muz", group: "Meyve", risk: "dikkatli" },
  { name: "Çilek", group: "Meyve", risk: "guvenli" },
  { name: "Yaban mersini", group: "Meyve", risk: "guvenli" },
  { name: "Portakal", group: "Meyve", risk: "dikkatli" },
  { name: "Mandalina", group: "Meyve", risk: "dikkatli" },
  { name: "Kivi", group: "Meyve", risk: "dikkatli" },
  { name: "Üzüm", group: "Meyve", risk: "dikkatli" },
  { name: "Ananas", group: "Meyve", risk: "dikkatli" },
  { name: "Elma", group: "Meyve", risk: "riskli" },
  { name: "Armut", group: "Meyve", risk: "riskli" },
  { name: "Karpuz", group: "Meyve", risk: "riskli" },
  { name: "Şeftali", group: "Meyve", risk: "riskli" },
  { name: "Kayısı", group: "Meyve", risk: "riskli" },
  { name: "Süt", group: "Süt ürünü", risk: "riskli" },
  { name: "Laktozsuz süt", group: "Süt ürünü", risk: "dikkatli" },
  { name: "Yoğurt", group: "Süt ürünü", risk: "dikkatli" },
  { name: "Laktozsuz yoğurt", group: "Süt ürünü", risk: "guvenli" },
  { name: "Kaşar peyniri", group: "Süt ürünü", risk: "dikkatli" },
  { name: "Beyaz peynir", group: "Süt ürünü", risk: "dikkatli" },
  { name: "Tereyağı", group: "Yağ", risk: "guvenli" },
  { name: "Zeytinyağı", group: "Yağ", risk: "guvenli" },
  { name: "Avokado", group: "Yağlı meyve", risk: "dikkatli" },
  { name: "Tavuk", group: "Protein", risk: "guvenli" },
  { name: "Hindi", group: "Protein", risk: "guvenli" },
  { name: "Dana eti", group: "Protein", risk: "guvenli" },
  { name: "Balık", group: "Protein", risk: "guvenli" },
  { name: "Yumurta", group: "Protein", risk: "guvenli" },
  { name: "Nohut", group: "Baklagil", risk: "riskli" },
  { name: "Mercimek", group: "Baklagil", risk: "riskli" },
  { name: "Fasulye", group: "Baklagil", risk: "riskli" },
  { name: "Bulgur", group: "Tahıl (gluten)", risk: "riskli" },
  { name: "Buğday ekmeği", group: "Tahıl (gluten)", risk: "riskli" },
  { name: "Arpa", group: "Tahıl (gluten)", risk: "riskli" },
  { name: "Çavdar", group: "Tahıl (gluten)", risk: "riskli" },
  { name: "Glutensiz ekmek", group: "Glutensiz ürün", risk: "dikkatli" },
  { name: "Badem (az porsiyon)", group: "Kuruyemiş", risk: "dikkatli" },
  { name: "Ceviz", group: "Kuruyemiş", risk: "guvenli" },
  { name: "Fındık", group: "Kuruyemiş", risk: "dikkatli" },
  { name: "Kaju", group: "Kuruyemiş", risk: "riskli" },
  { name: "Antep fıstığı", group: "Kuruyemiş", risk: "riskli" },
  { name: "Bal", group: "Tatlandırıcı", risk: "riskli" },
  { name: "Akçaağaç şurubu", group: "Tatlandırıcı", risk: "dikkatli" },
  { name: "Şeker", group: "Tatlandırıcı", risk: "dikkatli" },
];
